// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.221104.6

#pragma once
#ifndef WINRT_Microsoft_Toolkit_Win32_UI_XamlHost_1_H
#define WINRT_Microsoft_Toolkit_Win32_UI_XamlHost_1_H
#include "winrt/impl/Microsoft.Toolkit.Win32.UI.XamlHost.0.h"
WINRT_EXPORT namespace winrt::Microsoft::Toolkit::Win32::UI::XamlHost
{
    struct WINRT_IMPL_EMPTY_BASES IXamlApplication :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IXamlApplication>
    {
        IXamlApplication(std::nullptr_t = nullptr) noexcept {}
        IXamlApplication(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES IXamlApplicationFactory :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IXamlApplicationFactory>
    {
        IXamlApplicationFactory(std::nullptr_t = nullptr) noexcept {}
        IXamlApplicationFactory(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
}
#endif
