// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.221104.6

#pragma once
#ifndef WINRT_Microsoft_Toolkit_Win32_UI_XamlHost_2_H
#define WINRT_Microsoft_Toolkit_Win32_UI_XamlHost_2_H
#include "winrt/impl/Windows.Foundation.1.h"
#include "winrt/impl/Windows.Foundation.Collections.1.h"
#include "winrt/impl/Windows.UI.Xaml.1.h"
#include "winrt/impl/Windows.UI.Xaml.Markup.1.h"
#include "winrt/impl/Microsoft.Toolkit.Win32.UI.XamlHost.1.h"
WINRT_EXPORT namespace winrt::Microsoft::Toolkit::Win32::UI::XamlHost
{
    struct WINRT_IMPL_EMPTY_BASES XamlApplication : winrt::Microsoft::Toolkit::Win32::UI::XamlHost::IXamlApplication,
        impl::base<XamlApplication, winrt::Windows::UI::Xaml::Application>,
        impl::require<XamlApplication, winrt::Windows::Foundation::IClosable, winrt::Windows::UI::Xaml::IApplication, winrt::Windows::UI::Xaml::IApplication2, winrt::Windows::UI::Xaml::IApplication3, winrt::Windows::UI::Xaml::IApplicationOverrides, winrt::Windows::UI::Xaml::IApplicationOverrides2>
    {
        XamlApplication(std::nullptr_t) noexcept {}
        XamlApplication(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::Toolkit::Win32::UI::XamlHost::IXamlApplication(ptr, take_ownership_from_abi) {}
        explicit XamlApplication(param::vector<winrt::Windows::UI::Xaml::Markup::IXamlMetadataProvider> const& providers);
        XamlApplication();
    };
}
#endif
