namespace CppXaml
{
  runtimeclass XamlApplication : Windows.UI.Xaml.Application, Windows.UI.Xaml.Markup.IXamlMetadataProvider, Windows.Foundation.IClosable
  {
    XamlApplication();
    XamlApplication(Windows.Foundation.Collections.IVector<Windows.UI.Xaml.Markup.IXamlMetadataProvider> providers);
    Windows.Foundation.Collections.IVector<Windows.UI.Xaml.Markup.IXamlMetadataProvider> MetadataProviders{ get; };
    Windows.Foundation.IClosable WindowsXamlManager{ get; };
  }
}
