
namespace MarkupSample
{

    runtimeclass MainPage : Windows.UI.Xaml.Controls.Page, Windows.UI.Xaml.Data.INotifyPropertyChanged
    {
        MainPage();
        
        String InterfaceStr;
        String ImplString{ get; };
        Windows.UI.Xaml.Controls.Button OkButton;
        Windows.UI.Xaml.Documents.Hyperlink Link{ get; };
        Windows.UI.Xaml.Controls.Button PickFileButton;
        Int32 MyInt{ get; set; };
        
    }
}
